"""Add name property to UserBase model

Revision ID: 75c70f93123f
Revises: d735a26a42f8
Create Date: 2024-06-08 21:54:14.521721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c70f93123f'
down_revision: Union[str, None] = 'd735a26a42f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), nullable=False))
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
